name: api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }} ${{ secrets.DOCKER_HOST }}
      - name: Docker Build
        run: docker build -f ./docker/Dockerfile -t ${{github.repository}} .
      - name: Tags
        run: |
          docker tag ${{github.repository}} ${{ secrets.DOCKER_HOST }}/${{github.repository}}:${{github.sha}}
          docker tag ${{github.repository}} ${{ secrets.DOCKER_HOST }}/${{github.repository}}:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HOST }}/${{github.repository}}:${{github.sha}}
          docker push ${{ secrets.DOCKER_HOST }}/${{github.repository}}:latest
